name: Deploy website

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deployToTest:
    if: github.event_name == 'pull_request'
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ~/SaveTheDate-Emailer
            git fetch origin ${{ github.ref }}:${{ github.ref }} --force
            git reset --hard FETCH_HEAD

            cd Server
            docker build --build-arg NODE_VERSION=$(cat ../.nvmrc | tr -cd [:digit:].) -t wedding:${{ github.event.number }} .
            docker stop test_wedding || true
            docker rm test_wedding || true
            docker run -d --restart unless-stopped --net=docker_backend --ip=172.20.2.2 --name test_wedding --env-file ../../test.env -v /home/${{ secrets.USERNAME }}/invitations:/usr/src/app/invitations:ro wedding:${{ github.event.number }}

  deployProduction:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ~/SaveTheDate-Emailer
            git fetch origin
            git reset --hard origin/main
            git pull origin ${{ github.ref }}

            cd Server
            # Tag the image with the commit hash
            docker build --build-arg NODE_VERSION=$(cat ../.nvmrc | tr -cd [:digit:].) -t wedding:${{ github.sha }} .
            docker stop live_wedding|| true
            docker rm live_wedding || true
            docker run -d --restart unless-stopped --net=docker_backend --ip=172.20.2.1 --name live_wedding --env-file ../../production.env -v /home/${{ secrets.USERNAME }}/invitations:/usr/src/app/invitations:ro wedding:${{ github.sha }}
